### ISSUE TITLE
Taking photos lag

### ISSUE THREAD

**Issue by lucamoroz** [PrandiniUniPD/OCRCamera#12]
The effective taken photo is not the one displayed on the screen when the button is pressed, but it's a photo taken a considerable amount of time later

**Comment by Fisher4537** [comment]
How much is the time gap between the pressure of the botton and the take of the photo in your configuration? I tried only in a pixel API 25 and the gap is 1.25s.

**Comment by lucamoroz** [comment]
It takes about 5 seconds to take the effective picture plus at least more 5 seconds to extract the text

**Comment by PrandiniUniPD** [comment]
Resolved in #29
