### ISSUE TITLE
Rotated photo on some devices

### ISSUE THREAD

**Issue by lucamoroz** [PrandiniUniPD/OCRCamera#13]
On some devices the captured photo is rotated by 90 degrees

**Comment by GiovanniFurlan** [comment]
me too on a redmi 4x      7.1.2

**Comment by lucamoroz** [comment]
Here is proposed a solution which need an URI to get the image orientation and act accordingly:

https://stackoverflow.com/questions/14066038/why-does-an-image-captured-using-camera-intent-gets-rotated-on-some-devices-on-a

**Comment by PrandiniUniPD** [comment]
@GiovanniFurlan has implemented a possible solution for that. You can find it in the branch named CommonDemo.
In my Wileyfox Swift 2 Plus (API level 27 - Android 8.1) it works.

**Comment by PrandiniUniPD** [comment]
It works for my device, but if not for the others there is another guide here https://firebase.google.com/docs/ml-kit/android/recognize-text . This is the official guide for ml-kit, in this page there is an example of the code useful to recognize the orientation of the Image object.

**Comment by PrandiniUniPD** [comment]
I've checked more precisely the solution by @GiovanniFurlan but it's not complete.

**Comment by PrandiniUniPD** [comment]
I've opened a pull request with the possible solution ( #16 )
The branch where I've worked is named "RotationBug"

**Comment by PrandiniUniPD** [comment]
The pull request has been accepted because #20 has a code derived from #16 
In the Common Demo branch there is a version that use the gyroscope, it's not always the best method.
The proposed method is with the use of the Surface orientations.

**Comment by Nintenking** [comment]
Is this issue still active?

**Comment by PrandiniUniPD** [comment]
Last time some people have said that on their smartphones not work the proposed solution (in #16 there are more details).
In #29 there is another version of the CameraActivity, so when that pull request will be accepted we have to assure that this issue is definitely closed, otherwise for some people still the problem and this issue still opened until a solution.

**Comment by PrandiniUniPD** [comment]
On my smartphone with API level 27 this issue is solved with the version contained in the CommonDemo branch.
Anyone has this problem?

**Comment by Nintenking** [comment]
Tested on my smartphone, API level 26. Although I never actually experienced this problem before, I run anyway various tests with both device rotation activated and deactivated; the captured image was always the one expected, never wrongfully rotated.
Not a problem for me

**Comment by PrandiniUniPD** [comment]
Outdated
