### ISSUE TITLE
Problemi con CommonDemo

### ISSUE THREAD

**Issue by GiovanniFurlan** [PrandiniUniPD/OCRCamera#14]
Having some problems with version CommonDemo. 
When i take a picture happers the OCR activity with a white space instead of the taken photo, the OCR works so something arrives at OCR so i think there are some problem with displaying. With debug mode i've found this message.
there are some problems with buffer capabilities.
[screenshot from 2018-11-04 16-39-22](https://user-images.githubusercontent.com/44239656/47966297-13905900-e051-11e8-8350-1435c1533bc8.png)

Before take the photo
![screenshot from 2018-11-04 16-50-08](https://user-images.githubusercontent.com/44239656/47966357-b8129b00-e051-11e8-92f6-351aa8975ee4.png)

after take the photo
![screenshot from 2018-11-04 16-52-47](https://user-images.githubusercontent.com/44239656/47966395-19d30500-e052-11e8-96b4-465e83ec04bf.png)
![screenshot from 2018-11-04 16-52-54](https://user-images.githubusercontent.com/44239656/47966396-1dff2280-e052-11e8-86c8-8861fbae2025.png)

**Comment by lucamoroz** [comment]
Solved scaling the bitmap before showing it in the image view
