### ISSUE TITLE
Exposure discrepancy

### ISSUE THREAD

**Issue by AndreaTonUnipd** [PrandiniUniPD/OCRCamera#19]
There's a discrepancy in the exposure between live preview and photo taken.
Tried and found in: 
-Nexus 5X Emulator (API 25) w/ Webcam
-Pixel 2XL Emulator (API 28) w/ Webcam
-One Plus 2 (API 25) Rear Camera

**Comment by PrandiniUniPD** [comment]
Are you referring to #12 ?

**Comment by AndreaTonUnipd** [comment]
not talking about time, it's about light.

**Comment by PrandiniUniPD** [comment]
Outdated
