### ISSUE TITLE
Inefficiency introduced for respecting the OCRInterface

### ISSUE THREAD

**Issue by PrandiniUniPD** [PrandiniUniPD/OCRCamera#24]
The new TextExtractor accepted by the pull request #20 is useful to retrieve a String from the OCR and avoid a "single point of failure".
In the other hand it has introduced an inefficiency in the code (line 64, TextExtractor.java).
Any ideas to solve the problem of inefficiency and respect the actual OCRInterfece at the same time?
Could we accept this inefficiency for avoiding a "single point of failure"? Or have we to change the OCRInterface?

**Comment by PrandiniUniPD** [comment]
@EliaBedin and I have tested some alternatives with multiple threads, semaphores and other synchronization elements without success.

**Comment by PrandiniUniPD** [comment]
@lucamoroz has proposed a solution in the branch photo_testing, I'm going to open a pull request for requesting reviews and consequently include it in the code.

**Comment by leopardo-rossi-developer** [comment]
From your first comment it's not clear what kind of inefficiency has been introduced into the code. Can you explain it better please?

**Comment by PrandiniUniPD** [comment]
> From your first comment it's not clear what kind of inefficiency has been introduced into the code. Can you explain it better please?

It is in the commit b5dc984 at the line 64 of the TextExtractor.java where there is busy waiting (in #20 there are some explanations about this introduction).
However in the #25 there is a proposed solution for this issue.

**Comment by PrandiniUniPD** [comment]
In CommonDemo this issue is considered resolved.
