### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by Fisher4537** [PrandiniUniPD/OCRCamera#27]
The App crash istantaneusly when open with API level lower than 24.

**Comment by thomasporro** [comment]
In my phone (API 23) the app crash with an error in roundedbotton.xml. I resolved this just copying the file from the drawable-v24 folder to the drawable folder

**Comment by PrandiniUniPD** [comment]
There is a possible solution in #28, there are some statements in the wrong places (see ToDo for details about it)

**Comment by Fisher4537** [comment]
After #23 this issue is resolved. Great work !
