### ISSUE TITLE
Photo_button not working on emulator.

### ISSUE THREAD

**Issue by leopra** [PrandiniUniPD/OCRCamera#37]
On line 142 of CameraActivity there is a problem because the code checks orientationResult but on an emulator it is always setted as NULL as this parameter is setted with the onSensorChange method. In this way it never enters the if condition and the ResultActivity never starts.
For now i have disabled that IF to continue working on the application.
Credits: dottor Li

**Comment by frankplus** [comment]
I merged a fix, can you please verify that it is now working on the emulator?
