### ISSUE TITLE
branch downloadPhotosFromDb error when pressing "Download Photos"

### ISSUE THREAD

**Issue by leopra** [PrandiniUniPD/OCRCamera#91]
I keep receiving the status: Java.io.IOException: Connection is not open.

**Comment by stefanoromanello** [comment]
watching now

**Comment by stefanoromanello** [comment]
You have to enable storage permission manually to the app. I'm implementing right now the permission verification

**Comment by stefanoromanello** [comment]
Pushed a new version with the implementation of the permission request. Please close the issue if you have resolved the problem.

**Comment by leopra** [comment]
https://user-images.githubusercontent.com/44270170/49855008-28000800-fdec-11e8-97dd-b1d5f6a58a9f.png
Still not working for me.

**Comment by leopra** [comment]
Anyway now the app is working better because it is creating the textfile with login information

**Comment by stefanoromanello** [comment]
If youre connected to eduroam it will not work. Eduroam blocks ftp connection (at least from pc)
Try another internet connection, in general this is a problem of the client connection. Be sure to not be under a firewall
